language: go
go:
  - 1.12.x
  - 1.13.x
  - tip

env:
  - VERBOSE=1

matrix:
  allow_failures:
    - go: tip

before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/lint/golint

script:
  - make test
