language: go
go:
  - 1.9.x
  - 1.11.x
  - tip

env:
  - DEP_VERSION=0.5.0
  - VERBOSE=1

matrix:
  allow_failures:
    - go: tip

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

before_script:
  - go get golang.org/x/tools/cmd/cover

script:
  - make test
