language: go
go:
  - 1.4
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_script:
  - go get golang.org/x/tools/cmd/cover
script:
  - go test -v ./...
  - scripts/climate -o -t 80 .
