// Copyright (c) 2015 SUSE LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"os"
	"testing"
)

func testServiceOutput(t *testing.T, filePath string, expectedOutput string) {
	reader, err := os.Open(filePath)
	if err != nil {
		t.Fatal("Could not read JSON file...")
	}
	defer reader.Close()

	products, err := parseProducts(reader)
	if err != nil {
		t.Errorf(err.Error())
	}
	if len(products) != 1 {
		t.Fatalf("Unexpected number of products found. Got %d, expected %d", len(products), 1)
	}

	buf := bytes.Buffer{}
	dumpRepositories(&buf, products[0])

	result := buf.String()
	if result != expectedOutput {
		t.Errorf(result)
	}
}

func TestServiceOutputSLE12(t *testing.T) {
	const expectedOutput = `# generated by container-suseconnect

[SLES12-Updates]
name=SLES12-Updates for sle-12-x86_64
baseurl=https://smt.test.lan/repo/SUSE/Updates/SLE-SERVER/12/x86_64/update
autorefresh=1
enabled=1

[SLES12-Debuginfo-Updates]
name=SLES12-Debuginfo-Updates for sle-12-x86_64
baseurl=https://smt.test.lan/repo/SUSE/Updates/SLE-SERVER/12/x86_64/update_debug
autorefresh=1
enabled=0

[SLES12-Pool]
name=SLES12-Pool for sle-12-x86_64
baseurl=https://smt.test.lan/repo/SUSE/Products/SLE-SERVER/12/x86_64/product
autorefresh=0
enabled=1

[SLES12-Debuginfo-Pool]
name=SLES12-Debuginfo-Pool for sle-12-x86_64
baseurl=https://smt.test.lan/repo/SUSE/Products/SLE-SERVER/12/x86_64/product_debug
autorefresh=0
enabled=0

`
	testServiceOutput(t, "data/products-sle12.json", expectedOutput)
}

func TestServiceOutputSLE15(t *testing.T) {
	const expectedOutput = `# generated by container-suseconnect

[SLE15-Installer-Updates]
name=SLE15-Installer-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-INSTALLER/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Product-SLES15-Pool]
name=SLE-Product-SLES15-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Product-SLES/15/x86_64/product/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=1

[SLE-Product-SLES15-Updates]
name=SLE-Product-SLES15-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Product-SLES/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=1

[SLE-Product-SLES15-Debuginfo-Updates]
name=SLE-Product-SLES15-Debuginfo-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Product-SLES/15/x86_64/update_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Product-SLES15-Source-Pool]
name=SLE-Product-SLES15-Source-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Product-SLES/15/x86_64/product_source/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Product-SLES15-Debuginfo-Pool]
name=SLE-Product-SLES15-Debuginfo-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Product-SLES/15/x86_64/product_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Basesystem15-Updates]
name=SLE-Module-Basesystem15-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Basesystem/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=1

[SLE-Module-Basesystem15-Source-Pool]
name=SLE-Module-Basesystem15-Source-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15/x86_64/product_source/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Basesystem15-Debuginfo-Updates]
name=SLE-Module-Basesystem15-Debuginfo-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Basesystem/15/x86_64/update_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Module-Basesystem15-Pool]
name=SLE-Module-Basesystem15-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15/x86_64/product/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=1

[SLE-Module-Basesystem15-Debuginfo-Pool]
name=SLE-Module-Basesystem15-Debuginfo-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15/x86_64/product_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Server-Applications15-Updates]
name=SLE-Module-Server-Applications15-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Server-Applications/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=1

[SLE-Module-Server-Applications15-Debuginfo-Updates]
name=SLE-Module-Server-Applications15-Debuginfo-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Server-Applications/15/x86_64/update_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Module-Server-Applications15-Pool]
name=SLE-Module-Server-Applications15-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Server-Applications/15/x86_64/product/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=1

[SLE-Module-Server-Applications15-Debuginfo-Pool]
name=SLE-Module-Server-Applications15-Debuginfo-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Server-Applications/15/x86_64/product_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Server-Applications15-Source-Pool]
name=SLE-Module-Server-Applications15-Source-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Server-Applications/15/x86_64/product_source/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

`

	testServiceOutput(t, "data/products-sle15.json", expectedOutput)
}

func TestServiceOutputSLE15WithCustomModules(t *testing.T) {
	os.Setenv(
		"ENABLED_MODULES",
		"sle-module-desktop-applications,sle-module-development-tools",
	)
	const expectedOutput = `# generated by container-suseconnect

[SLE15-Installer-Updates]
name=SLE15-Installer-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-INSTALLER/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Product-SLES15-Pool]
name=SLE-Product-SLES15-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Product-SLES/15/x86_64/product/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=1

[SLE-Product-SLES15-Updates]
name=SLE-Product-SLES15-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Product-SLES/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=1

[SLE-Product-SLES15-Debuginfo-Updates]
name=SLE-Product-SLES15-Debuginfo-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Product-SLES/15/x86_64/update_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Product-SLES15-Source-Pool]
name=SLE-Product-SLES15-Source-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Product-SLES/15/x86_64/product_source/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Product-SLES15-Debuginfo-Pool]
name=SLE-Product-SLES15-Debuginfo-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Product-SLES/15/x86_64/product_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Basesystem15-Updates]
name=SLE-Module-Basesystem15-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Basesystem/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=1

[SLE-Module-Basesystem15-Source-Pool]
name=SLE-Module-Basesystem15-Source-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15/x86_64/product_source/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Basesystem15-Debuginfo-Updates]
name=SLE-Module-Basesystem15-Debuginfo-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Basesystem/15/x86_64/update_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Module-Basesystem15-Pool]
name=SLE-Module-Basesystem15-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15/x86_64/product/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=1

[SLE-Module-Basesystem15-Debuginfo-Pool]
name=SLE-Module-Basesystem15-Debuginfo-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15/x86_64/product_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Server-Applications15-Updates]
name=SLE-Module-Server-Applications15-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Server-Applications/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=1

[SLE-Module-Server-Applications15-Debuginfo-Updates]
name=SLE-Module-Server-Applications15-Debuginfo-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Server-Applications/15/x86_64/update_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Module-Server-Applications15-Pool]
name=SLE-Module-Server-Applications15-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Server-Applications/15/x86_64/product/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=1

[SLE-Module-Server-Applications15-Debuginfo-Pool]
name=SLE-Module-Server-Applications15-Debuginfo-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Server-Applications/15/x86_64/product_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Server-Applications15-Source-Pool]
name=SLE-Module-Server-Applications15-Source-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Server-Applications/15/x86_64/product_source/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Desktop-Applications15-Updates]
name=SLE-Module-Desktop-Applications15-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Desktop-Applications/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=1

[SLE-Module-Desktop-Applications15-Debuginfo-Updates]
name=SLE-Module-Desktop-Applications15-Debuginfo-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Desktop-Applications/15/x86_64/update_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Module-Desktop-Applications15-Pool]
name=SLE-Module-Desktop-Applications15-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Desktop-Applications/15/x86_64/product/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=1

[SLE-Module-Desktop-Applications15-Debuginfo-Pool]
name=SLE-Module-Desktop-Applications15-Debuginfo-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Desktop-Applications/15/x86_64/product_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-Desktop-Applications15-Source-Pool]
name=SLE-Module-Desktop-Applications15-Source-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Desktop-Applications/15/x86_64/product_source/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-DevTools15-Updates]
name=SLE-Module-DevTools15-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Development-Tools/15/x86_64/update/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=1

[SLE-Module-DevTools15-Debuginfo-Updates]
name=SLE-Module-DevTools15-Debuginfo-Updates for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Updates/SLE-Module-Development-Tools/15/x86_64/update_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=1
enabled=0

[SLE-Module-DevTools15-Pool]
name=SLE-Module-DevTools15-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Development-Tools/15/x86_64/product/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=1

[SLE-Module-DevTools15-Debuginfo-Pool]
name=SLE-Module-DevTools15-Debuginfo-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Development-Tools/15/x86_64/product_debug/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

[SLE-Module-DevTools15-Source-Pool]
name=SLE-Module-DevTools15-Source-Pool for sle-15-x86_64
baseurl=http://smt-ec2.susecloud.net/repo/SUSE/Products/SLE-Module-Development-Tools/15/x86_64/product_source/?credentials=SMT-http_smt-ec2_susecloud_net
autorefresh=0
enabled=0

`

	testServiceOutput(t, "data/products-sle15.json", expectedOutput)
}
