package main

import (
	"fmt"
	"io"
)

func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

func DumpRepositories(w io.Writer, product Product) {

	fmt.Fprintf(w, "# generated by container-suseconnect\n")
	fmt.Fprintf(w, "\n")
	for _, repo := range product.Repositories {
		fmt.Fprintf(w, "[%s]\n", repo.Name)
		fmt.Fprintf(w, "name=%s\n", repo.Description)
		fmt.Fprintf(w, "baseurl=%s\n", repo.URL)
		fmt.Fprintf(w, "autorefresh=%d\n", boolToInt(repo.Autorefresh))
		fmt.Fprintf(w, "enabled=%d\n", boolToInt(repo.Enabled))
		fmt.Fprintf(w, "\n")
	}
}
