---
name: Run the unit tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.13", "1.14", "1.16", "1.17", "1.18", "1.19"]

    name: Go unit tests
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: install dependencies
        run: |
          go get golang.org/x/tools/cmd/cover
          go get golang.org/x/lint/golint

      - name: compile
        run: make

      - name: run the tests
        run: make test
