name: Golang Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GOFIPS140: v1.0.0
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Build
        run: go build -v ./...

      - name: make tests
        run: make test
